spring:
  datasource:
    url: jdbc:h2:mem:securitydb
#    username: training
#    password: training
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
#        dialect: org.hibernate.dialect.Oracle10gDialect
#  security:
#    user:
#      name: user
#      password: password
logging:
  level:
    com:
      spring:
        security: debug
    org:
      springframework:
        security: debug