#spring:
 # datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/mathisipdb
#    username: training
#    password: training
#  jpa:
 #   show-sql: true
 #   hibernate:
 #     ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.Oracle10gDialect
#  security:
#    user:
#      name: user
#      password: password
logging:
  level:
    com:
      spring:
        security: debug
    org:
      springframework:
        security: debug
spring:
  h2:
    console:
      enabled: true